set -x ISE_BASE_URL 'https://198.18.133.27'
set -x ISE_USERNAME 'admin' 
set -x ISE_PASSWORD '324655'
set -x ISE_DEBUG 'true'
set -x ISE_SSL_VERIFY 'false'
set -x ISE_USE_API_GATEWAY 'false'
set -x ISE_USE_CSRF_TOKEN 'false'
set -x ISE_SINGLE_REQUEST_TIMEOUT '60'