package ciscoise

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// Provider definition of schema(configuration), resources(CRUD) operations and dataSources(query)
func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"base_url": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_BASE_URL", nil),
			},
			"username": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_USERNAME", nil),
			},
			"password": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_PASSWORD", nil),
			},
			"debug": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_DEBUG", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"ssl_verify": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				Sensitive:    true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_SSL_VERIFY", "true"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"use_api_gateway": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_USE_API_GATEWAY", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"use_csrf_token": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_USE_CSRF_TOKEN", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
		},
		ResourcesMap: map[string]*schema.Resource{},
		DataSourcesMap: map[string]*schema.Resource{
			"ise_mnt_account_status":                dataSourceMntAccountStatus(),
			"ise_mnt_athentication_status":          dataSourceMntAthenticationStatus(),
			"ise_backup_last_status":                dataSourceBackupLastStatus(),
			"ise_csr":                               dataSourceCsr(),
			"ise_csr_export":                        dataSourceCsrExport(),
			"ise_system_certificate":                dataSourceSystemCertificate(),
			"ise_trusted_certificate":               dataSourceTrustedCertificate(),
			"ise_trusted_certificate_export":        dataSourceTrustedCertificateExport(),
			"ise_mnt_session_disconnect":            dataSourceMntSessionDisconnect(),
			"ise_mnt_session_reauthentication":      dataSourceMntSessionReauthentication(),
			"ise_node_group":                        dataSourceNodeGroup(),
			"ise_node_deployment":                   dataSourceNodeDeployment(),
			"ise_pan_ha":                            dataSourcePanHa(),
			"ise_device_administration_command_set": dataSourceDeviceAdministrationCommandSet(),
			"ise_device_administration_conditions":  dataSourceDeviceAdministrationConditions(),
			"ise_device_administration_conditions_for_authentication_rule":   dataSourceDeviceAdministrationConditionsForAuthenticationRule(),
			"ise_device_administration_conditions_for_authorization_rule":    dataSourceDeviceAdministrationConditionsForAuthorizationRule(),
			"ise_device_administration_conditions_for_policy_set":            dataSourceDeviceAdministrationConditionsForPolicySet(),
			"ise_device_administration_dictionary_attributes_authentication": dataSourceDeviceAdministrationDictionaryAttributesAuthentication(),
			"ise_device_administration_dictionary_attributes_authorization":  dataSourceDeviceAdministrationDictionaryAttributesAuthorization(),
			"ise_device_administration_dictionary_attributes_policy_set":     dataSourceDeviceAdministrationDictionaryAttributesPolicySet(),
			"ise_device_administration_identity_stores":                      dataSourceDeviceAdministrationIDentityStores(),
			"ise_device_administration_network_conditions":                   dataSourceDeviceAdministrationNetworkConditions(),
			"ise_device_administration_policy_set":                           dataSourceDeviceAdministrationPolicySet(),
			"ise_device_administration_authentication_rules":                 dataSourceDeviceAdministrationAuthenticationRules(),
			"ise_device_administration_authorization_rules":                  dataSourceDeviceAdministrationAuthorizationRules(),
			"ise_device_administration_local_exception_rules":                dataSourceDeviceAdministrationLocalExceptionRules(),
			"ise_device_administration_global_exception_rules":               dataSourceDeviceAdministrationGlobalExceptionRules(),
			"ise_device_administration_profiles":                             dataSourceDeviceAdministrationProfiles(),
			"ise_device_administration_service_names":                        dataSourceDeviceAdministrationServiceNames(),
			"ise_device_administration_time_date_conditions":                 dataSourceDeviceAdministrationTimeDateConditions(),
			"ise_aci_bindings":                           dataSourceAciBindings(),
			"ise_aci_settings":                           dataSourceAciSettings(),
			"ise_active_directory":                       dataSourceActiveDirectory(),
			"ise_admin_user":                             dataSourceAdminUser(),
			"ise_allowed_protocols":                      dataSourceAllowedProtocols(),
			"ise_anc_endpoint":                           dataSourceAncEndpoint(),
			"ise_anc_endpoint_bulk_monitor_status":       dataSourceAncEndpointBulkMonitorStatus(),
			"ise_anc_policy":                             dataSourceAncPolicy(),
			"ise_anc_policy_bulk_monitor_status":         dataSourceAncPolicyBulkMonitorStatus(),
			"ise_authorization_profile":                  dataSourceAuthorizationProfile(),
			"ise_byod_portal":                            dataSourceByodPortal(),
			"ise_certificate_profile":                    dataSourceCertificateProfile(),
			"ise_certificate_template":                   dataSourceCertificateTemplate(),
			"ise_deployment":                             dataSourceDeployment(),
			"ise_downloadable_acl":                       dataSourceDownloadableACL(),
			"ise_egress_matrix_cell":                     dataSourceEgressMatrixCell(),
			"ise_egress_matrix_cell_bulk_monitor_status": dataSourceEgressMatrixCellBulkMonitorStatus(),
			"ise_endpoint":                               dataSourceEndpoint(),
			"ise_endpoint_bulk_monitor_status":           dataSourceEndpointBulkMonitorStatus(),
			"ise_endpoint_get_rejected_endpoints":        dataSourceEndpointGetRejectedEndpoints(),
			"ise_endpoint_group":                         dataSourceEndpointGroup(),
			"ise_external_radius_server":                 dataSourceExternalRadiusServer(),
			"ise_filter_policy":                          dataSourceFilterPolicy(),
			"ise_guest_location":                         dataSourceGuestLocation(),
			"ise_guest_smtp_notification_settings":       dataSourceGuestSmtpNotificationSettings(),
			"ise_guest_ssid":                             dataSourceGuestSSID(),
			"ise_guest_type":                             dataSourceGuestType(),
			"ise_guest_user":                             dataSourceGuestUser(),
			"ise_guest_user_bulk_monitor_status":         dataSourceGuestUserBulkMonitorStatus(),
			"ise_hotspot_portal":                         dataSourceHotspotPortal(),
			"ise_identity_group":                         dataSourceIDentityGroup(),
			"ise_id_store_sequence":                      dataSourceIDStoreSequence(),
			"ise_internal_user":                          dataSourceInternalUser(),
			"ise_my_device_portal":                       dataSourceMyDevicePortal(),
			"ise_network_device":                         dataSourceNetworkDevice(),
			"ise_network_device_bulk_monitor_status":     dataSourceNetworkDeviceBulkMonitorStatus(),
			"ise_network_device_group":                   dataSourceNetworkDeviceGroup(),
			"ise_node":                                   dataSourceNode(),
			"ise_native_supplicant_profile":              dataSourceNativeSupplicantProfile(),
			"ise_system_config_version":                  dataSourceSystemConfigVersion(),
			"ise_portal":                                 dataSourcePortal(),
			"ise_portal_global_setting":                  dataSourcePortalGlobalSetting(),
			"ise_portal_theme":                           dataSourcePortalTheme(),
			"ise_profiler_profile":                       dataSourceProfilerProfile(),
			"ise_px_grid_node":                           dataSourcePxGridNode(),
			"ise_radius_server_sequence":                 dataSourceRadiusServerSequence(),
			"ise_rest_id_store":                          dataSourceRestIDStore(),
			"ise_self_registered_portal":                 dataSourceSelfRegisteredPortal(),
			"ise_session_service_node":                   dataSourceSessionServiceNode(),
			"ise_sg_acl":                                 dataSourceSgACL(),
			"ise_sg_acl_bulk_monitor_status":             dataSourceSgACLBulkMonitorStatus(),
			"ise_sg_mapping":                             dataSourceSgMapping(),
			"ise_sg_mapping_bulk_monitor_status":         dataSourceSgMappingBulkMonitorStatus(),
			"ise_sg_mapping_group":                       dataSourceSgMappingGroup(),
			"ise_sg_mapping_group_bulk_monitor_status":   dataSourceSgMappingGroupBulkMonitorStatus(),
			"ise_sgt":                                                 dataSourceSgt(),
			"ise_sgt_bulk_monitor_status":                             dataSourceSgtBulkMonitorStatus(),
			"ise_sg_to_vn_to_vlan":                                    dataSourceSgToVnToVLAN(),
			"ise_sg_to_vn_to_vlan_bulk_monitor_status":                dataSourceSgToVnToVLANBulkMonitorStatus(),
			"ise_sms_provider":                                        dataSourceSmsProvider(),
			"ise_sponsored_guest_portal":                              dataSourceSponsoredGuestPortal(),
			"ise_sponsor_group":                                       dataSourceSponsorGroup(),
			"ise_sponsor_group_member":                                dataSourceSponsorGroupMember(),
			"ise_sponsor_portal":                                      dataSourceSponsorPortal(),
			"ise_support_bundle_status":                               dataSourceSupportBundleStatus(),
			"ise_sxp_connections":                                     dataSourceSxpConnections(),
			"ise_sxp_connections_bulk_monitor_status":                 dataSourceSxpConnectionsBulkMonitorStatus(),
			"ise_sxp_local_bindings":                                  dataSourceSxpLocalBindings(),
			"ise_sxp_local_bindings_bulk_monitor_status":              dataSourceSxpLocalBindingsBulkMonitorStatus(),
			"ise_sxp_vpns":                                            dataSourceSxpVpns(),
			"ise_sxp_vpns_bulk_monitor_status":                        dataSourceSxpVpnsBulkMonitorStatus(),
			"ise_tacacs_command_sets":                                 dataSourceTacacsCommandSets(),
			"ise_tacacs_external_servers":                             dataSourceTacacsExternalServers(),
			"ise_tacacs_profile":                                      dataSourceTacacsProfile(),
			"ise_tacacs_server_sequence":                              dataSourceTacacsServerSequence(),
			"ise_telemetry_info":                                      dataSourceTelemetryInfo(),
			"ise_mnt_failure_reasons":                                 dataSourceMntFailureReasons(),
			"ise_pxgrid_failures":                                     dataSourcePxgridFailures(),
			"ise_network_access_conditions":                           dataSourceNetworkAccessConditions(),
			"ise_network_access_conditions_for_authentication_rule":   dataSourceNetworkAccessConditionsForAuthenticationRule(),
			"ise_network_access_conditions_for_authorization_rule":    dataSourceNetworkAccessConditionsForAuthorizationRule(),
			"ise_network_access_conditions_for_policy_set":            dataSourceNetworkAccessConditionsForPolicySet(),
			"ise_network_access_dictionary":                           dataSourceNetworkAccessDictionary(),
			"ise_network_access_dictionary_attribute":                 dataSourceNetworkAccessDictionaryAttribute(),
			"ise_network_access_dictionary_attributes_authentication": dataSourceNetworkAccessDictionaryAttributesAuthentication(),
			"ise_network_access_dictionary_attributes_authorization":  dataSourceNetworkAccessDictionaryAttributesAuthorization(),
			"ise_network_access_dictionary_attributes_policy_set":     dataSourceNetworkAccessDictionaryAttributesPolicySet(),
			"ise_network_access_identity_stores":                      dataSourceNetworkAccessIDentityStores(),
			"ise_network_access_network_condition":                    dataSourceNetworkAccessNetworkCondition(),
			"ise_network_access_policy_set":                           dataSourceNetworkAccessPolicySet(),
			"ise_network_access_authentication_rules":                 dataSourceNetworkAccessAuthenticationRules(),
			"ise_network_access_authorization_rules":                  dataSourceNetworkAccessAuthorizationRules(),
			"ise_network_access_local_exception_rules":                dataSourceNetworkAccessLocalExceptionRules(),
			"ise_network_access_global_exception_rules":               dataSourceNetworkAccessGlobalExceptionRules(),
			"ise_network_access_profiles":                             dataSourceNetworkAccessProfiles(),
			"ise_network_access_security_groups":                      dataSourceNetworkAccessSecurityGroups(),
			"ise_network_access_service_name":                         dataSourceNetworkAccessServiceName(),
			"ise_network_access_time_date_conditions":                 dataSourceNetworkAccessTimeDateConditions(),
			"ise_node_replication_status":                             dataSourceNodeReplicationStatus(),
			"ise_repository":                                          dataSourceRepository(),
			"ise_repository_files":                                    dataSourceRepositoryFiles(),
			"ise_mnt_sessions_by_session_id":                          dataSourceMntSessionsBySessionID(),
			"ise_mnt_session_active_count":                            dataSourceMntSessionActiveCount(),
			"ise_mnt_session_active_list":                             dataSourceMntSessionActiveList(),
			"ise_mnt_session_auth_list":                               dataSourceMntSessionAuthList(),
			"ise_mnt_session_by_ip":                                   dataSourceMntSessionByIP(),
			"ise_mnt_session_by_nas_ip":                               dataSourceMntSessionByNasIP(),
			"ise_mnt_session_by_mac":                                  dataSourceMntSessionByMac(),
			"ise_mnt_session_posture_count":                           dataSourceMntSessionPostureCount(),
			"ise_mnt_session_profiler_count":                          dataSourceMntSessionProfilerCount(),
			"ise_mnt_session_by_username":                             dataSourceMntSessionByUsername(),
			"ise_tasks":                                               dataSourceTasks(),
			"ise_mnt_version":                                         dataSourceMntVersion(),
			"ise_resource_version":                                    dataSourceResourceVersion(),
		},
		ConfigureContextFunc: providerConfigure,
	}
}
