package ciscoise

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// Provider definition of schema(configuration), resources(CRUD) operations and dataSources(query)
func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"base_url": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_BASE_URL", nil),
			},
			"username": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_USERNAME", nil),
			},
			"password": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("ISE_PASSWORD", nil),
			},
			"debug": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_DEBUG", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"ssl_verify": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				Sensitive:    true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_SSL_VERIFY", "true"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"use_api_gateway": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_USE_API_GATEWAY", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
			"use_csrf_token": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				DefaultFunc:  schema.EnvDefaultFunc("ISE_USE_CSRF_TOKEN", "false"),
				ValidateFunc: validateStringHasValueFunc([]string{"true", "false"}),
			},
		},
		ResourcesMap: map[string]*schema.Resource{},
		DataSourcesMap: map[string]*schema.Resource{
			"ciscoise_mnt_account_status":                                         dataSourceMntAccountStatus(),
			"ciscoise_mnt_athentication_status":                                   dataSourceMntAthenticationStatus(),
			"ciscoise_backup_last_status":                                         dataSourceBackupLastStatus(),
			"ciscoise_csr":                                                        dataSourceCsr(),
			"ciscoise_csr_export":                                                 dataSourceCsrExport(),
			"ciscoise_system_certificate":                                         dataSourceSystemCertificate(),
			"ciscoise_trusted_certificate":                                        dataSourceTrustedCertificate(),
			"ciscoise_trusted_certificate_export":                                 dataSourceTrustedCertificateExport(),
			"ciscoise_mnt_session_disconnect":                                     dataSourceMntSessionDisconnect(),
			"ciscoise_mnt_session_reauthentication":                               dataSourceMntSessionReauthentication(),
			"ciscoise_node_group":                                                 dataSourceNodeGroup(),
			"ciscoise_node_deployment":                                            dataSourceNodeDeployment(),
			"ciscoise_pan_ha":                                                     dataSourcePanHa(),
			"ciscoise_device_administration_command_set":                          dataSourceDeviceAdministrationCommandSet(),
			"ciscoise_device_administration_conditions":                           dataSourceDeviceAdministrationConditions(),
			"ciscoise_device_administration_conditions_for_authentication_rule":   dataSourceDeviceAdministrationConditionsForAuthenticationRule(),
			"ciscoise_device_administration_conditions_for_authorization_rule":    dataSourceDeviceAdministrationConditionsForAuthorizationRule(),
			"ciscoise_device_administration_conditions_for_policy_set":            dataSourceDeviceAdministrationConditionsForPolicySet(),
			"ciscoise_device_administration_dictionary_attributes_authentication": dataSourceDeviceAdministrationDictionaryAttributesAuthentication(),
			"ciscoise_device_administration_dictionary_attributes_authorization":  dataSourceDeviceAdministrationDictionaryAttributesAuthorization(),
			"ciscoise_device_administration_dictionary_attributes_policy_set":     dataSourceDeviceAdministrationDictionaryAttributesPolicySet(),
			"ciscoise_device_administration_identity_stores":                      dataSourceDeviceAdministrationIDentityStores(),
			"ciscoise_device_administration_network_conditions":                   dataSourceDeviceAdministrationNetworkConditions(),
			"ciscoise_device_administration_policy_set":                           dataSourceDeviceAdministrationPolicySet(),
			"ciscoise_device_administration_authentication_rules":                 dataSourceDeviceAdministrationAuthenticationRules(),
			"ciscoise_device_administration_authorization_rules":                  dataSourceDeviceAdministrationAuthorizationRules(),
			"ciscoise_device_administration_local_exception_rules":                dataSourceDeviceAdministrationLocalExceptionRules(),
			"ciscoise_device_administration_global_exception_rules":               dataSourceDeviceAdministrationGlobalExceptionRules(),
			"ciscoise_device_administration_profiles":                             dataSourceDeviceAdministrationProfiles(),
			"ciscoise_device_administration_service_names":                        dataSourceDeviceAdministrationServiceNames(),
			"ciscoise_device_administration_time_date_conditions":                 dataSourceDeviceAdministrationTimeDateConditions(),
			"ciscoise_aci_bindings":                                               dataSourceAciBindings(),
			"ciscoise_aci_settings":                                               dataSourceAciSettings(),
			"ciscoise_active_directory":                                           dataSourceActiveDirectory(),
			"ciscoise_admin_user":                                                 dataSourceAdminUser(),
			"ciscoise_allowed_protocols":                                          dataSourceAllowedProtocols(),
			"ciscoise_anc_endpoint":                                               dataSourceAncEndpoint(),
			"ciscoise_anc_endpoint_bulk_monitor_status":                           dataSourceAncEndpointBulkMonitorStatus(),
			"ciscoise_anc_policy":                                                 dataSourceAncPolicy(),
			"ciscoise_anc_policy_bulk_monitor_status":                             dataSourceAncPolicyBulkMonitorStatus(),
			"ciscoise_authorization_profile":                                      dataSourceAuthorizationProfile(),
			"ciscoise_byod_portal":                                                dataSourceByodPortal(),
			"ciscoise_certificate_profile":                                        dataSourceCertificateProfile(),
			"ciscoise_certificate_template":                                       dataSourceCertificateTemplate(),
			"ciscoise_deployment":                                                 dataSourceDeployment(),
			"ciscoise_downloadable_acl":                                           dataSourceDownloadableACL(),
			"ciscoise_egress_matrix_cell":                                         dataSourceEgressMatrixCell(),
			"ciscoise_egress_matrix_cell_bulk_monitor_status":                     dataSourceEgressMatrixCellBulkMonitorStatus(),
			"ciscoise_endpoint":                                                   dataSourceEndpoint(),
			"ciscoise_endpoint_bulk_monitor_status":                               dataSourceEndpointBulkMonitorStatus(),
			"ciscoise_endpoint_get_rejected_endpoints":                            dataSourceEndpointGetRejectedEndpoints(),
			"ciscoise_endpoint_group":                                             dataSourceEndpointGroup(),
			"ciscoise_external_radius_server":                                     dataSourceExternalRadiusServer(),
			"ciscoise_filter_policy":                                              dataSourceFilterPolicy(),
			"ciscoise_guest_location":                                             dataSourceGuestLocation(),
			"ciscoise_guest_smtp_notification_settings":                           dataSourceGuestSmtpNotificationSettings(),
			"ciscoise_guest_ssid":                                                 dataSourceGuestSSID(),
			"ciscoise_guest_type":                                                 dataSourceGuestType(),
			"ciscoise_guest_user":                                                 dataSourceGuestUser(),
			"ciscoise_guest_user_bulk_monitor_status":                             dataSourceGuestUserBulkMonitorStatus(),
			"ciscoise_hotspot_portal":                                             dataSourceHotspotPortal(),
			"ciscoise_identity_group":                                             dataSourceIDentityGroup(),
			"ciscoise_id_store_sequence":                                          dataSourceIDStoreSequence(),
			"ciscoise_internal_user":                                              dataSourceInternalUser(),
			"ciscoise_my_device_portal":                                           dataSourceMyDevicePortal(),
			"ciscoise_network_device":                                             dataSourceNetworkDevice(),
			"ciscoise_network_device_bulk_monitor_status":                         dataSourceNetworkDeviceBulkMonitorStatus(),
			"ciscoise_network_device_group":                                       dataSourceNetworkDeviceGroup(),
			"ciscoise_node":                                                       dataSourceNode(),
			"ciscoise_native_supplicant_profile":                                  dataSourceNativeSupplicantProfile(),
			"ciscoise_system_config_version":                                      dataSourceSystemConfigVersion(),
			"ciscoise_portal":                                                     dataSourcePortal(),
			"ciscoise_portal_global_setting":                                      dataSourcePortalGlobalSetting(),
			"ciscoise_portal_theme":                                               dataSourcePortalTheme(),
			"ciscoise_profiler_profile":                                           dataSourceProfilerProfile(),
			"ciscoise_px_grid_node":                                               dataSourcePxGridNode(),
			"ciscoise_radius_server_sequence":                                     dataSourceRadiusServerSequence(),
			"ciscoise_rest_id_store":                                              dataSourceRestIDStore(),
			"ciscoise_self_registered_portal":                                     dataSourceSelfRegisteredPortal(),
			"ciscoise_session_service_node":                                       dataSourceSessionServiceNode(),
			"ciscoise_sg_acl":                                                     dataSourceSgACL(),
			"ciscoise_sg_acl_bulk_monitor_status":                                 dataSourceSgACLBulkMonitorStatus(),
			"ciscoise_sg_mapping":                                                 dataSourceSgMapping(),
			"ciscoise_sg_mapping_bulk_monitor_status":                             dataSourceSgMappingBulkMonitorStatus(),
			"ciscoise_sg_mapping_group":                                           dataSourceSgMappingGroup(),
			"ciscoise_sg_mapping_group_bulk_monitor_status":                       dataSourceSgMappingGroupBulkMonitorStatus(),
			"ciscoise_sgt":                                                        dataSourceSgt(),
			"ciscoise_sgt_bulk_monitor_status":                                    dataSourceSgtBulkMonitorStatus(),
			"ciscoise_sg_to_vn_to_vlan":                                           dataSourceSgToVnToVLAN(),
			"ciscoise_sg_to_vn_to_vlan_bulk_monitor_status":                       dataSourceSgToVnToVLANBulkMonitorStatus(),
			"ciscoise_sms_provider":                                               dataSourceSmsProvider(),
			"ciscoise_sponsored_guest_portal":                                     dataSourceSponsoredGuestPortal(),
			"ciscoise_sponsor_group":                                              dataSourceSponsorGroup(),
			"ciscoise_sponsor_group_member":                                       dataSourceSponsorGroupMember(),
			"ciscoise_sponsor_portal":                                             dataSourceSponsorPortal(),
			"ciscoise_support_bundle_status":                                      dataSourceSupportBundleStatus(),
			"ciscoise_sxp_connections":                                            dataSourceSxpConnections(),
			"ciscoise_sxp_connections_bulk_monitor_status":                        dataSourceSxpConnectionsBulkMonitorStatus(),
			"ciscoise_sxp_local_bindings":                                         dataSourceSxpLocalBindings(),
			"ciscoise_sxp_local_bindings_bulk_monitor_status":                     dataSourceSxpLocalBindingsBulkMonitorStatus(),
			"ciscoise_sxp_vpns":                                                   dataSourceSxpVpns(),
			"ciscoise_sxp_vpns_bulk_monitor_status":                               dataSourceSxpVpnsBulkMonitorStatus(),
			"ciscoise_tacacs_command_sets":                                        dataSourceTacacsCommandSets(),
			"ciscoise_tacacs_external_servers":                                    dataSourceTacacsExternalServers(),
			"ciscoise_tacacs_profile":                                             dataSourceTacacsProfile(),
			"ciscoise_tacacs_server_sequence":                                     dataSourceTacacsServerSequence(),
			"ciscoise_telemetry_info":                                             dataSourceTelemetryInfo(),
			"ciscoise_mnt_failure_reasons":                                        dataSourceMntFailureReasons(),
			"ciscoise_pxgrid_failures":                                            dataSourcePxgridFailures(),
			"ciscoise_network_access_conditions":                                  dataSourceNetworkAccessConditions(),
			"ciscoise_network_access_conditions_for_authentication_rule":          dataSourceNetworkAccessConditionsForAuthenticationRule(),
			"ciscoise_network_access_conditions_for_authorization_rule":           dataSourceNetworkAccessConditionsForAuthorizationRule(),
			"ciscoise_network_access_conditions_for_policy_set":                   dataSourceNetworkAccessConditionsForPolicySet(),
			"ciscoise_network_access_dictionary":                                  dataSourceNetworkAccessDictionary(),
			"ciscoise_network_access_dictionary_attribute":                        dataSourceNetworkAccessDictionaryAttribute(),
			"ciscoise_network_access_dictionary_attributes_authentication":        dataSourceNetworkAccessDictionaryAttributesAuthentication(),
			"ciscoise_network_access_dictionary_attributes_authorization":         dataSourceNetworkAccessDictionaryAttributesAuthorization(),
			"ciscoise_network_access_dictionary_attributes_policy_set":            dataSourceNetworkAccessDictionaryAttributesPolicySet(),
			"ciscoise_network_access_identity_stores":                             dataSourceNetworkAccessIDentityStores(),
			"ciscoise_network_access_network_condition":                           dataSourceNetworkAccessNetworkCondition(),
			"ciscoise_network_access_policy_set":                                  dataSourceNetworkAccessPolicySet(),
			"ciscoise_network_access_authentication_rules":                        dataSourceNetworkAccessAuthenticationRules(),
			"ciscoise_network_access_authorization_rules":                         dataSourceNetworkAccessAuthorizationRules(),
			"ciscoise_network_access_local_exception_rules":                       dataSourceNetworkAccessLocalExceptionRules(),
			"ciscoise_network_access_global_exception_rules":                      dataSourceNetworkAccessGlobalExceptionRules(),
			"ciscoise_network_access_profiles":                                    dataSourceNetworkAccessProfiles(),
			"ciscoise_network_access_security_groups":                             dataSourceNetworkAccessSecurityGroups(),
			"ciscoise_network_access_service_name":                                dataSourceNetworkAccessServiceName(),
			"ciscoise_network_access_time_date_conditions":                        dataSourceNetworkAccessTimeDateConditions(),
			"ciscoise_node_replication_status":                                    dataSourceNodeReplicationStatus(),
			"ciscoise_repository":                                                 dataSourceRepository(),
			"ciscoise_repository_files":                                           dataSourceRepositoryFiles(),
			"ciscoise_mnt_sessions_by_session_id":                                 dataSourceMntSessionsBySessionID(),
			"ciscoise_mnt_session_active_count":                                   dataSourceMntSessionActiveCount(),
			"ciscoise_mnt_session_active_list":                                    dataSourceMntSessionActiveList(),
			"ciscoise_mnt_session_auth_list":                                      dataSourceMntSessionAuthList(),
			"ciscoise_mnt_session_by_ip":                                          dataSourceMntSessionByIP(),
			"ciscoise_mnt_session_by_nas_ip":                                      dataSourceMntSessionByNasIP(),
			"ciscoise_mnt_session_by_mac":                                         dataSourceMntSessionByMac(),
			"ciscoise_mnt_session_posture_count":                                  dataSourceMntSessionPostureCount(),
			"ciscoise_mnt_session_profiler_count":                                 dataSourceMntSessionProfilerCount(),
			"ciscoise_mnt_session_by_username":                                    dataSourceMntSessionByUsername(),
			"ciscoise_tasks":                                                      dataSourceTasks(),
			"ciscoise_mnt_version":                                                dataSourceMntVersion(),
			"ciscoise_resource_version":                                           dataSourceResourceVersion(),
		},
		ConfigureContextFunc: providerConfigure,
	}
}
